name: go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set Up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: checkout go
      uses: actions/checkout@v2
    
    - name: test
      uses: make test
      

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:

    #     aws-region: eu-west-1

    